### ISSUE TITLE
Request for transfer: power-assert-js organization

### ISSUE THREAD

**Issue by twada** [watilde/karma-power-assert#10]
Hi, I'm the author of [power-assert](https://github.com/power-assert-js/power-assert) and created an organization [power-assert-js](https://github.com/power-assert-js) to help users finding related products easily.

Today I want you to join us and transfer this project to power-assert-js organization.

If you agree with me, first I invite you to our organization, then request you to transfer this repo. Please see [about repository transfers](https://help.github.com/articles/about-repository-transfers/) for details. If you do not want to transfer, it's no problem at all ;)

Thanks!

**Comment by watilde** [comment]
Hiya, OFC I'd love to transfer this repo to the org since the code is stable already, and it makes maintenance easier. Could I have the invitation?

**Comment by watilde** [comment]
Plus, I will give you a permission to publish the module on the npm registry :)

**Comment by twada** [comment]
@watilde Thanks & Invited!

**Comment by watilde** [comment]
It's shipped as `v1.0.0`, and you are in the list of the publisher team on the registry;

    $ npm info karma-power-assert versions
    [ '0.0.1', '0.0.2', '0.0.3', '0.0.4', '0.0.5', '1.0.0' ]

The team: https://www.npmjs.com/package/karma-power-assert/access

Thanks! Closing as resolved.

**Comment by twada** [comment]
Great 🎉
